# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.5
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: anoopreddy240@gmail.com
author_name: anoopreddykunta
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: NFT

